# Site settings
title: John Starich
tagline: Full Stack Software Engineer
description: > # this means to ignore newlines until "baseurl:"
  Full stack software engineer writing services for IBM Cloud. Currently works on the IBM Cloud Kubernetes Service and its supporting services.
email: johnstarich@johnstarich.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johnstarich.com" # the base hostname & protocol for your site
github_username: JohnStarich
logo: /favicon.png
timezone: America/Chicago
future: false
unpublished: false
limit_posts: 0
show_dir_listing: false

# Build settings
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: pretty
collections:
  skills:
    layout: skill
    output: true
  experiences:
    output: true

defaults:
  - scope:
      type: skills
    values:
      layout: skill
  - scope:
      type: experiences
    values:
      hidden: true
