# Site settings
title: John Starich
tagline: Full stack software engineer
description: > # this means to ignore newlines until "baseurl:"
  All about me.
email: johnstarich@johnstarich.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johnstarich.com" # the base hostname & protocol for your site
github_username: JohnStarich
timezone: America/Chicago

# Build settings
markdown: kramdown
gems: [jekyll-assets, octopress-autoprefixer]
sass:
    style: compressed

permalink: pretty
collections:
    skills:
        output: true

