# Site settings
title: John Starich
tagline: Hack. Explore. Teach.
description: > # this means to ignore newlines until "baseurl:"
  John turns ideas into results, explores the outdoors, and guides others through the tech world. He currently works on the IBM Cloud Kubernetes Service and is actively programming in dozens of projects.
email: johnstarich@johnstarich.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johnstarich.com" # the base hostname & protocol for your site
github_username: JohnStarich
logo: /favicon.png
timezone: America/Chicago
future: false
unpublished: false
limit_posts: 0
show_dir_listing: false

# Build settings
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

permalink: pretty
paginate: 10
paginate_path: "/blog/page:num/"
excerpt_separator: "\n\n\n"
collections:
  skills:
    layout: skill
    output: true
  experiences:
    output: true

defaults:
  - scope:
      type: skills
    values:
      layout: skill
  - scope:
      type: experiences
    values:
      hidden: true

optional_front_matter:
  remove_originals: true
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
